services:
  sdk-generator:
    image: gradle:7-jdk17-corretto
    container_name: sdk-generator
    volumes:
      - .:/workspace
      - ../chargebee-sdks:/sdks
      # gradle and maven cache
      - gradle-cache:/root/.gradle
      - maven-cache:/root/.m2
    working_dir: /workspace
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - GRADLE_OPTS=-Dorg.gradle.daemon=false
      - BASE_DIR=/sdks
    entrypoint: ["scripts/sdk-gen.sh"]

volumes:
  gradle-cache:
    driver: local
  maven-cache:
    driver: local
