name: ðŸ› Bug Report
description: Create a detailed report to help us reproduce and fix the issue

body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting a bug, please make sure the issue hasn't already been reported by checking [existing issues](https://github.com/chargebee/sdk-generator/issues).

        If this is a **question**, consider starting a [discussion](https://github.com/chargebee/sdk-generator/discussions) instead.

  - type: textarea
    attributes:
      label: ðŸ› Describe the Bug
      description: |
        Provide a **clear and concise** description of the bug and what you expected to happen.

        If available, link to a public gist or repository with reproduction code: https://gist.github.com
      placeholder: |
        A clear and concise description of the issue and how it differs from expected behavior.
    validations:
      required: true

  - type: textarea
    attributes:
      label: ðŸ” Steps to Reproduce
      description: |
        Describe how to reproduce the bug step-by-step.

        You can paste CLI commands and code samples between triple backticks (```) for formatting.
      placeholder: |
        1. Run the SDK generator with the following command:

           ```bash
           ./gradlew run --args="-i spec.json -l PHP_V4 -o ../chargebee-php/php/src"
           ```

        2. Check the output directory for generated code  
        3. Observe any errors, missing files, or incorrect structures
    validations:
      required: true

  - type: textarea
    attributes:
      label: ðŸ§ª Expected vs Actual Behavior
      description: What did you expect to happen, and what actually happened?
      placeholder: |
        I expected the PHP SDK to include the retry wrapper, but it was missing the generated class.
    validations:
      required: true

  - type: input
    attributes:
      label: ðŸŒ Environment Info
      description: Please provide any relevant environment details such as OS, Java/Gradle version, CLI version.
      placeholder: e.g. Java 17, Gradle 8.2.1, macOS 14.4, CLI v1.3.2

  - type: dropdown
    attributes:
      label: ðŸ”¢ Severity
      description: How severe is the issue?
      options:
        - â— Blocking: Cannot proceed without a fix
        - ðŸž Major: Serious bug but has a workaround
        - ðŸ§Š Minor: Cosmetic or edge case
        - ðŸ¤· Uncertain

  - type: markdown
    attributes:
      value: >
        Thanks for contributing ðŸŽ‰ Your bug report helps us improve the Chargebee SDK generator for everyone.