package com.chargebee.sdk.go.v4;

public class Constants {
  public static final String INT_SIXTY_FOUR = "int64";
  public static final String INT_THIRTY_TWO = "int32";
  public static final String UNIX_TIME = "unix-time";
  public static final String JSON_RAW_MESSAGE = "json.RawMessage";
  public static final String ENUM = "\"";
  public static final String ENUM_MODEL_IMPORT =
      "\"github.com/chargebee/chargebee-go/v3/";
  public static final String UNDERSCORE_ENUM = "_Enum";
  public static final String SORT_BY = "sort_by";
  public static final String STRING_TYPE = "string";
  public static final String ENUM_DOT = ".";
  public static final String MAP_STRING_INTERFACE = "map[string]interface{}";
  public static final String FILTER = "*";
  public static final String ENUM_WITH_DELIMITER = "";
  public static final String FILE_HEADER = "// Code generated by sdk-generator; DO NOT EDIT.\npackage chargebee\n";

  private Constants() {}
}
